server:
  port: 8080
spring:
  application:
    name: eureka-client

eureka:
  instance:
    hostname: localhost
    ip-address: 192.168.1.120
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka/, http://${eureka.instance.ip-address}:8762/eureka/, http://${eureka.instance.ip-address}:8763/eureka/


